name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          docker build -t fastapi-app .
      
      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Add actual deployment commands here (e.g., SCP, SSH, Kubernetes, etc.)

