name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 --push -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-app --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app --platform managed --region ${{ secrets.GCP_REGION }} --allow-unauthenticated