name: CD Pipeline

on:
  push:
    branches:
      - main  # Runs only when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ 1. Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ 2. Set up SSH for GCP
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.68.79.114 >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"  # Start SSH agent
          ssh-add ~/.ssh/id_rsa    # Add the key

      # ✅ 3. Install Python & dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # ✅ 4. Deploy to GCP via SSH
      - name: Deploy Application to GCP
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no dreamfyre@34.68.79.114 << 'EOF'
            cd ~/fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi-app  # Adjust if needed
          EOF

      # ✅ 5. Restart Nginx to apply changes (if using Nginx)
      - name: Restart Nginx
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no dreamfyre@34.68.79.114 "sudo systemctl restart nginx"
